/*
 * CobradorConvertirView.java
 */

package cobradorconvertir;

import au.com.bytecode.opencsv.CSVReader;
import java.awt.Color;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Enumeration;
import java.util.LinkedHashSet;
import java.util.Vector;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import org.json.me.JSONException;
import org.json.me.JSONObject;

/**
 * The application's main frame.
 */
public class CobradorConvertirView extends FrameView {

    public CobradorConvertirView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = CobradorConvertirApp.getApplication().getMainFrame();
            aboutBox = new CobradorConvertirAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        CobradorConvertirApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonExpendiosCSVJSON = new javax.swing.JButton();
        jButtonExpendiosJSONCSV = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaExpendiosMessages = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonConsignatariasCSVJSON = new javax.swing.JButton();
        jButtonConsignatariasJSONCSV = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaConsignatariasMessages = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cobradorconvertir.CobradorConvertirApp.class).getContext().getResourceMap(CobradorConvertirView.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jButtonExpendiosCSVJSON.setText(resourceMap.getString("jButtonExpendiosCSVJSON.text")); // NOI18N
        jButtonExpendiosCSVJSON.setName("jButtonExpendiosCSVJSON"); // NOI18N
        jButtonExpendiosCSVJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpendiosCSVJSONActionPerformed(evt);
            }
        });

        jButtonExpendiosJSONCSV.setText(resourceMap.getString("jButtonExpendiosJSONCSV.text")); // NOI18N
        jButtonExpendiosJSONCSV.setName("jButtonExpendiosJSONCSV"); // NOI18N
        jButtonExpendiosJSONCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpendiosJSONCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonExpendiosCSVJSON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExpendiosJSONCSV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExpendiosCSVJSON)
                    .addComponent(jButtonExpendiosJSONCSV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setName("jPanel4"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextAreaExpendiosMessages.setColumns(20);
        jTextAreaExpendiosMessages.setEditable(false);
        jTextAreaExpendiosMessages.setRows(5);
        jTextAreaExpendiosMessages.setName("jTextAreaExpendiosMessages"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaExpendiosMessages);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        jButtonConsignatariasCSVJSON.setText(resourceMap.getString("jButtonConsignatariasCSVJSON.text")); // NOI18N
        jButtonConsignatariasCSVJSON.setName("jButtonConsignatariasCSVJSON"); // NOI18N
        jButtonConsignatariasCSVJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsignatariasCSVJSONActionPerformed(evt);
            }
        });

        jButtonConsignatariasJSONCSV.setText(resourceMap.getString("jButtonConsignatariasJSONCSV.text")); // NOI18N
        jButtonConsignatariasJSONCSV.setName("jButtonConsignatariasJSONCSV"); // NOI18N
        jButtonConsignatariasJSONCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsignatariasJSONCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConsignatariasCSVJSON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsignatariasJSONCSV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsignatariasCSVJSON)
                    .addComponent(jButtonConsignatariasJSONCSV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setName("jPanel6"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextAreaConsignatariasMessages.setColumns(20);
        jTextAreaConsignatariasMessages.setEditable(false);
        jTextAreaConsignatariasMessages.setRows(5);
        jTextAreaConsignatariasMessages.setName("jTextAreaConsignatariasMessages"); // NOI18N
        jScrollPane2.setViewportView(jTextAreaConsignatariasMessages);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cobradorconvertir.CobradorConvertirApp.class).getContext().getActionMap(CobradorConvertirView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExpendiosCSVJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpendiosCSVJSONActionPerformed
        // TODO add your handling code here:
        String sFileGetParent = "";

        JFileChooser jfilechooser = new JFileChooser();
        jfilechooser.setMultiSelectionEnabled(true);
        jfilechooser.setCurrentDirectory(new File("c:\\"));
        int iRetVal = jfilechooser.showDialog(jPanel1, null);

        if (iRetVal == JFileChooser.APPROVE_OPTION) {
            File[] fSelecteds = jfilechooser.getSelectedFiles();
            Rutas[] aRutasParsed = new Rutas[fSelecteds.length];

            for (int i=0; i<fSelecteds.length; i++) {
                String sFileAP = fSelecteds[i].getAbsolutePath();
                sFileGetParent = fSelecteds[i].getParent();
                aRutasParsed[i] = ParseCSV(sFileAP);
            }

            Vector vRutaCobrador = new Vector();
            for (int i=0; i<aRutasParsed.length; i++) {
                Rutas rutasCurrent = aRutasParsed[i];
                Enumeration eRutasCurrent = rutasCurrent.GetVectorRutas().elements();
                while (eRutasCurrent.hasMoreElements()) {
                    Ruta rutaCurrent = (Ruta) eRutasCurrent.nextElement();
                    vRutaCobrador.addElement(rutaCurrent);
                }
            }

            Rutas rutasAll = new Rutas();
            rutasAll.SetVectorRutas(vRutaCobrador);

            Enumeration eRutasAllVectorRutas = rutasAll.GetVectorRutas().elements();
            Vector vCobradores = new Vector();
            while (eRutasAllVectorRutas.hasMoreElements()) {
                Ruta ruta = (Ruta) eRutasAllVectorRutas.nextElement();
                vCobradores.addElement(ruta.GetCobrador());
            }

            Vector vCobradoresUniq = new Vector(new LinkedHashSet(vCobradores));

            Enumeration eCobradores = vCobradoresUniq.elements();
            int iContadorCobrador = 0;
            while (eCobradores.hasMoreElements()) {
                String sCobradorCurrent = (String) eCobradores.nextElement();
                Vector vCobradorRutas = new Vector();

                eRutasAllVectorRutas = rutasAll.GetVectorRutas().elements();
                while (eRutasAllVectorRutas.hasMoreElements()) {
                    Ruta ruta = (Ruta) eRutasAllVectorRutas.nextElement();
                    if (sCobradorCurrent.equals(ruta.GetCobrador())) {
                        vCobradorRutas.addElement(ruta);
                    }
                }

                Rutas rutasCobrador = new Rutas();
                rutasCobrador.SetVectorRutas(vCobradorRutas);

                boolean bWriteResult = WriteJSONCobradorFile(rutasCobrador, sFileGetParent, iContadorCobrador);
                if (bWriteResult) {
                    jTextAreaExpendiosMessages.setForeground(Color.black);
                    jTextAreaExpendiosMessages.append("OK: " + GetMessages() + System.getProperty("line.separator"));
                } else {
                    jTextAreaExpendiosMessages.setForeground(Color.red);
                    jTextAreaExpendiosMessages.setText("ERROR: " + GetMessages());
                    break;
                }

                iContadorCobrador++;
            }
        }
    }//GEN-LAST:event_jButtonExpendiosCSVJSONActionPerformed

    private void jButtonExpendiosJSONCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpendiosJSONCSVActionPerformed
        // TODO add your handling code here:
        JFileChooser jfilechooser = new JFileChooser();
        jfilechooser.setCurrentDirectory(new File("c:\\"));
        int iRetVal = jfilechooser.showDialog(jPanel1, null);

        if (iRetVal == JFileChooser.APPROVE_OPTION) {
            File fSelected = jfilechooser.getSelectedFile();
            String sFileAP = fSelected.getAbsolutePath();

            try {
                String sFileFull = "";
                BufferedReader in = new BufferedReader(new FileReader(sFileAP));
                String str;
                while ((str = in.readLine()) != null) {
                    sFileFull = sFileFull + str;
                }
                in.close();

                Rutas RUTAS = new Rutas(sFileFull);

                String sCSVFull = "EMPLEADO;ZONARUTA;RAZONSOC;DIRECCION;CODIGOCLI;FECHAMOV;ENTREGAS;DEVOLUCION;FALTANTES;SOBRANTES;VALORUNITA;COBRADO;VALORFEC;VALORCOM;NOMPU;FEPAGO;ADICIONA;RESTANTE;ENTREGO"+System.getProperty("line.separator");
                String sCurrentProducto = "";
                String sSufixProducto = "";
                Enumeration enumRutas = RUTAS.GetVectorRutas().elements();
                while (enumRutas.hasMoreElements()) {
                    String sCSVRuta = "EMPLEADO;ZONARUTA;RAZONSOC;DIRECCION;CODIGOCLI;FECHAMOV;ENTREGAS;DEVOLUCION;FALTANTES;SOBRANTES;VALORUNITA;COBRADO;VALORFEC;VALORCOM;NOMPU;FEPAGO;ADICIONA;RESTANTE;ENTREGO"+System.getProperty("line.separator");
                    Ruta ruta = (Ruta) enumRutas.nextElement();
                    Enumeration enumExpendios = ruta.GetVectorExpendios().elements();
                    while (enumExpendios.hasMoreElements()) {
                        Expendio expendio = (Expendio) enumExpendios.nextElement();
                        Enumeration enumFechas = expendio.GetVectorFechas().elements();
                        while (enumFechas.hasMoreElements()) {
                            Fecha fecha = (Fecha) enumFechas.nextElement();

                            sCSVFull = sCSVFull + ruta.GetCobrador() + ";" + ruta.GetZona() + ";" + expendio.GetNombre() + ";" + expendio.GetDireccion() + ";" + expendio.GetCodigoCliente() + ";" + fecha.GetFecha() + ";" + fecha.GetEntregados() + ";" + fecha.GetDevueltos() + ";" + fecha.GetFaltantes() + ";" + fecha.GetSobrantes() + ";" + fecha.GetValorUnitario() + ";" + fecha.GetCobrado() + ";" + fecha.GetValor() + ";" + expendio.GetCompendio() + ";" + ruta.GetProducto() + ";" + ruta.GetFecha() + ";" + fecha.GetAdicionales() + ";" + fecha.GetRestantes() + ";" + fecha.GetEntrego() + System.getProperty("line.separator");
                            sCSVRuta = sCSVRuta + ruta.GetCobrador() + ";" + ruta.GetZona() + ";" + expendio.GetNombre() + ";" + expendio.GetDireccion() + ";" + expendio.GetCodigoCliente() + ";" + fecha.GetFecha() + ";" + fecha.GetEntregados() + ";" + fecha.GetDevueltos() + ";" + fecha.GetFaltantes() + ";" + fecha.GetSobrantes() + ";" + fecha.GetValorUnitario() + ";" + fecha.GetCobrado() + ";" + fecha.GetValor() + ";" + expendio.GetCompendio() + ";" + ruta.GetProducto() + ";" + ruta.GetFecha() + ";" + fecha.GetAdicionales() + ";" + fecha.GetRestantes() + ";" + fecha.GetEntrego() + System.getProperty("line.separator");

                            sCurrentProducto = ruta.GetProducto();
                        }
                    }


                    if (sCurrentProducto.equalsIgnoreCase("LA PATRIA") || sCurrentProducto.equalsIgnoreCase("PATRIA")) {
                        sSufixProducto = "_LP";
                    }
                    if (sCurrentProducto.equalsIgnoreCase("NUEVO ESTADIO")) {
                        sSufixProducto = "_NE";
                    }
                    if (sCurrentProducto.equalsIgnoreCase("QHUBO") || sCurrentProducto.equalsIgnoreCase("Q HUBO")) {
                        sSufixProducto = "_QH";
                    }

                    String sFullName = fSelected.getAbsolutePath();
                    int idx = sFullName.indexOf(".json");
                    String sFileNew = sFullName.substring(0, idx) + sSufixProducto + ".csv";
                    String sFileOutput = sFileNew;
                    BufferedWriter out = new BufferedWriter(new FileWriter(sFileOutput));
                    out.write(sCSVRuta);
                    out.close();

                    jTextAreaExpendiosMessages.setForeground(Color.black);
                    jTextAreaExpendiosMessages.append("OK: Generado archivo " + "'" + sFileOutput + "'." + System.getProperty("line.separator"));
                }

                String sFullName = fSelected.getAbsolutePath();
                int idx = sFullName.indexOf(".json");
                String sFileNew = sFullName.substring(0, idx)+".csv";
                String sFileOutput = sFileNew;
                BufferedWriter out = new BufferedWriter(new FileWriter(sFileOutput));
                out.write(sCSVFull);
                out.close();


                jTextAreaExpendiosMessages.setForeground(Color.black);
                jTextAreaExpendiosMessages.append("OK: Generado archivo "+"'"+sFileOutput+"'."+System.getProperty("line.separator"));

            } catch (IOException ioex) {
                jTextAreaExpendiosMessages.setForeground(Color.red);
                jTextAreaExpendiosMessages.append("ERROR: "+ioex.toString()+System.getProperty("line.separator"));
                ioex.printStackTrace();
            } catch (Exception ex) {
                jTextAreaExpendiosMessages.setForeground(Color.red);
                jTextAreaExpendiosMessages.append("ERROR: "+ex.toString()+System.getProperty("line.separator"));
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonExpendiosJSONCSVActionPerformed

    private void jButtonConsignatariasCSVJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsignatariasCSVJSONActionPerformed
        // TODO add your handling code here:
        String sFileGetParent = "";

        JFileChooser jfilechooser = new JFileChooser();
        jfilechooser.setMultiSelectionEnabled(true);
        jfilechooser.setCurrentDirectory(new File("c:\\"));
        int iRetVal = jfilechooser.showDialog(jPanel1, null);

        if (iRetVal == JFileChooser.APPROVE_OPTION) {
            File[] fSelecteds = jfilechooser.getSelectedFiles();
            RutasConsignatarias[] aRutasConsignatariasParsed = new RutasConsignatarias[fSelecteds.length];

            for (int i=0; i<fSelecteds.length; i++) {
                String sFileAP = fSelecteds[i].getAbsolutePath();
                sFileGetParent = fSelecteds[i].getParent();
                aRutasConsignatariasParsed[i] = ParseCSVConsignatarias(sFileAP);
            }

            Vector vRutaConsignatariasCobrador = new Vector();
            for (int i=0; i<aRutasConsignatariasParsed.length; i++) {
                RutasConsignatarias rutasconsignatariasCurrent = aRutasConsignatariasParsed[i];
                Enumeration eRutasConsignatariasCurrent = rutasconsignatariasCurrent.GetVectorRutas().elements();
                while (eRutasConsignatariasCurrent.hasMoreElements()) {
                    RutaConsignatarias rutaconsignatariasCurrent = (RutaConsignatarias) eRutasConsignatariasCurrent.nextElement();
                    vRutaConsignatariasCobrador.addElement(rutaconsignatariasCurrent);
                }
            }

            RutasConsignatarias rutasconsignatariasAll = new RutasConsignatarias();
            rutasconsignatariasAll.SetVectorRutas(vRutaConsignatariasCobrador);

            Enumeration eRutasConsignatariasAllVectorRutas = rutasconsignatariasAll.GetVectorRutas().elements();
            Vector vCobradores = new Vector();
            while (eRutasConsignatariasAllVectorRutas.hasMoreElements()) {
                RutaConsignatarias rutaconsignatarias = (RutaConsignatarias) eRutasConsignatariasAllVectorRutas.nextElement();
                vCobradores.addElement(rutaconsignatarias.GetCobrador());
            }

            Vector vCobradoresUniq = new Vector(new LinkedHashSet(vCobradores));

            Enumeration eCobradores = vCobradoresUniq.elements();
            int iContadorCobrador = 0;
            while (eCobradores.hasMoreElements()) {
                String sCobradorCurrent = (String) eCobradores.nextElement();
                Vector vCobradorRutas = new Vector();

                eRutasConsignatariasAllVectorRutas = rutasconsignatariasAll.GetVectorRutas().elements();
                while (eRutasConsignatariasAllVectorRutas.hasMoreElements()) {
                    RutaConsignatarias rutaconsignatarias = (RutaConsignatarias) eRutasConsignatariasAllVectorRutas.nextElement();
                    if (sCobradorCurrent.equals(rutaconsignatarias.GetCobrador())) {
                        vCobradorRutas.addElement(rutaconsignatarias);
                    }
                }

                RutasConsignatarias rutasconsignatariasCobrador = new RutasConsignatarias();
                rutasconsignatariasCobrador.SetVectorRutas(vCobradorRutas);

                boolean bWriteResult = WriteJSONCobradorFileConsignatarias(rutasconsignatariasCobrador, sFileGetParent, iContadorCobrador);
                if (bWriteResult) {
                    jTextAreaConsignatariasMessages.setForeground(Color.black);
                    jTextAreaConsignatariasMessages.append("OK: " + GetMessages() + System.getProperty("line.separator"));
                } else {
                    jTextAreaConsignatariasMessages.setForeground(Color.red);
                    jTextAreaConsignatariasMessages.append("ERROR: " + GetMessages());
                    break;
                }

                iContadorCobrador++;
            }
        }
    }//GEN-LAST:event_jButtonConsignatariasCSVJSONActionPerformed

    private void jButtonConsignatariasJSONCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsignatariasJSONCSVActionPerformed
        // TODO add your handling code here:
        JFileChooser jfilechooser = new JFileChooser();
        jfilechooser.setCurrentDirectory(new File("c:\\"));
        int iRetVal = jfilechooser.showDialog(jPanel1, null);

        if (iRetVal == JFileChooser.APPROVE_OPTION) {
            File fSelected = jfilechooser.getSelectedFile();
            String sFileAP = fSelected.getAbsolutePath();

            try {
                String sFileFull = "";
                BufferedReader in = new BufferedReader(new FileReader(sFileAP));
                String str;
                while ((str = in.readLine()) != null) {
                    sFileFull = sFileFull + str;
                }
                in.close();

                RutasConsignatarias RUTAS = new RutasConsignatarias(sFileFull);

                String sCSVFull = "EMPLEADO;ZONARUTA;NOMBRE;NOMPU;RAZONSOC;CODIGOCLI;FECHAMOV;ENTREGAS;DEVOLUCION;FALTANTES;VALORUNITA;VALORCOM;FEPAGO;NUMEROF;COBRADO;ADICIONA;RESTANTE;ENTREGO"+System.getProperty("line.separator");
                //String sCSVFull = "EMPLEADO;ZONARUTA;RAZONSOC;DIRECCION;CODIGOCLI;FECHAMOV;ENTREGAS;DEVOLUCION;FALTANTES;SOBRANTES;VALORUNITA;COBRADO;VALORFEC;VALORCOM;NOMPU;FEPAGO"+System.getProperty("line.separator");
                //String sCSVFull = "EMPLEADO;ZONARUTA;NOMBRE;NOMPU;RAZONSOC;CODIGOCLI;FECHAMOV;ENTREGAS;DEVOLUCION;FALTANTES;VALORUNITA;FEPAGO;NUMEROF"+System.getProperty("line.separator");
                String sCurrentProducto = "";
                String sSufixProducto = "";
                Enumeration enumRutas = RUTAS.GetVectorRutas().elements();
                while (enumRutas.hasMoreElements()) {
                    String sCSVRuta = "EMPLEADO;ZONARUTA;NOMBRE;NOMPU;RAZONSOC;CODIGOCLI;FECHAMOV;ENTREGAS;DEVOLUCION;FALTANTES;VALORUNITA;VALORCOM;FEPAGO;NUMEROF;COBRADO;ADICIONA;RESTANTE;ENTREGO"+System.getProperty("line.separator");
                    RutaConsignatarias ruta = (RutaConsignatarias) enumRutas.nextElement();
                    Enumeration enumRazonesSociales = ruta.GetVectorRazonSocial().elements();
                    while (enumRazonesSociales.hasMoreElements()) {
                        RazonSocialConsignatarias razonsocial = (RazonSocialConsignatarias) enumRazonesSociales.nextElement();
                        Enumeration enumFacturas = razonsocial.GetVectorFacturas().elements();
                        while (enumFacturas.hasMoreElements()) {
                            FacturaConsignatarias factura = (FacturaConsignatarias) enumFacturas.nextElement();
                            Enumeration enumFechas = factura.GetVectorFechas().elements();
                            while (enumFechas.hasMoreElements()) {
                                FechaConsignatarias fecha = (FechaConsignatarias) enumFechas.nextElement();

                                sCSVFull = sCSVFull + ruta.GetCobrador() + ";" + razonsocial.GetZona() + ";" + razonsocial.GetNombreRuta() + ";" + ruta.GetProducto() + ";" + razonsocial.GetConsignataria() + ";" + razonsocial.GetCodigo() + ";" + fecha.GetFecha() + ";" + fecha.GetEntregados() + ";" + fecha.GetDevueltos() + ";" + fecha.GetFaltantes() + ";" + fecha.GetValorUnitario() + ";" + factura.GetCompendio() + ";" + factura.GetFechaPago() + ";" + factura.GetNoFactura() + ";" + fecha.GetCobrado() + ";" + fecha.GetAdicionales() + ";" + fecha.GetRestantes() + ";" + fecha.GetEntrego() + System.getProperty("line.separator");
                                sCSVRuta = sCSVRuta + ruta.GetCobrador() + ";" + razonsocial.GetZona() + ";" + razonsocial.GetNombreRuta() + ";" + ruta.GetProducto() + ";" + razonsocial.GetConsignataria() + ";" + razonsocial.GetCodigo() + ";" + fecha.GetFecha() + ";" + fecha.GetEntregados() + ";" + fecha.GetDevueltos() + ";" + fecha.GetFaltantes() + ";" + fecha.GetValorUnitario() + ";" + factura.GetCompendio() + ";" + factura.GetFechaPago() + ";" + factura.GetNoFactura() + ";" + fecha.GetCobrado() + ";" + fecha.GetAdicionales() + ";" + fecha.GetRestantes() + ";" + fecha.GetEntrego() + System.getProperty("line.separator");

                                sCurrentProducto = ruta.GetProducto();
                            }
                        }
                    }

                    if (sCurrentProducto.equalsIgnoreCase("LA PATRIA") || sCurrentProducto.equalsIgnoreCase("PATRIA")) {
                        sSufixProducto = "_LP";
                    }
                    if (sCurrentProducto.equalsIgnoreCase("NUEVO ESTADIO")) {
                        sSufixProducto = "_NE";
                    }
                    if (sCurrentProducto.equalsIgnoreCase("QHUBO") || sCurrentProducto.equalsIgnoreCase("Q HUBO")) {
                        sSufixProducto = "_QH";
                    }

                    String sFullName = fSelected.getAbsolutePath();
                    int idx = sFullName.indexOf(".json");
                    String sFileNew = sFullName.substring(0, idx) + sSufixProducto + ".csv";
                    String sFileOutput = sFileNew;
                    BufferedWriter out = new BufferedWriter(new FileWriter(sFileOutput));
                    out.write(sCSVRuta);
                    out.close();

                    jTextAreaConsignatariasMessages.setForeground(Color.black);
                    jTextAreaConsignatariasMessages.append("OK: Generado archivo " + "'" + sFileOutput + "'." + System.getProperty("line.separator"));
                }

                String sFullName = fSelected.getAbsolutePath();
                int idx = sFullName.indexOf(".json");
                String sFileNew = sFullName.substring(0, idx)+".csv";
                String sFileOutput = sFileNew;
                BufferedWriter out = new BufferedWriter(new FileWriter(sFileOutput));
                out.write(sCSVFull);
                out.close();


                jTextAreaConsignatariasMessages.setForeground(Color.black);
                jTextAreaConsignatariasMessages.append("OK: Generado archivo "+"'"+sFileOutput+"'."+System.getProperty("line.separator"));

            } catch (IOException ioex) {
                jTextAreaConsignatariasMessages.setForeground(Color.red);
                jTextAreaConsignatariasMessages.append("ERROR: "+ioex.toString()+System.getProperty("line.separator"));
                ioex.printStackTrace();
            } catch (Exception ex) {
                jTextAreaConsignatariasMessages.setForeground(Color.red);
                jTextAreaConsignatariasMessages.append("ERROR: "+ex.toString()+System.getProperty("line.separator"));
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonConsignatariasJSONCSVActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsignatariasCSVJSON;
    private javax.swing.JButton jButtonConsignatariasJSONCSV;
    private javax.swing.JButton jButtonExpendiosCSVJSON;
    private javax.swing.JButton jButtonExpendiosJSONCSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaConsignatariasMessages;
    private javax.swing.JTextArea jTextAreaExpendiosMessages;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;


    private String sMessages;
    private boolean bSuccess;

    private boolean bEsEntregar = false;


    private void SetMessages(String sMsg) {
        this.sMessages = sMsg;
    }

    private String GetMessages() {
        return this.sMessages;
    }


    public boolean GetSuccess() {
        return this.bSuccess;
    }

    public void SetSuccess(boolean suc) {
        this.bSuccess = suc;
    }


    public boolean GetEsEntregar() {
        return this.bEsEntregar;
    }

    public void SetEsEntregar(boolean esentregar) {
        this.bEsEntregar = esentregar;
    }


    private Rutas ParseCSV(String sCSVFile) {
        int contador = 0;
        Rutas rutas = new Rutas();
        Ruta ruta = new Ruta();
        Expendio expendio = new Expendio();
        Fecha fecha = new Fecha();

        Vector vFechas = new Vector();
        Vector vExpendios = new Vector();
        Vector vRutas = new Vector();
        Vector vRUTAS = new Vector();

        try {
            CSVReader reader = new CSVReader(new FileReader(sCSVFile), ';');
            String[] nextLine = reader.readNext();
            String sColumnaPrueba = "";
            //String sColumnaPrueba = nextLine[17];
            try {
                sColumnaPrueba = nextLine[17];
                SetEsEntregar(true);
            } catch (ArrayIndexOutOfBoundsException aioobex) {
                SetEsEntregar(false);
                SetMessages(aioobex.toString());
                aioobex.printStackTrace();
            }

            String sCobradorAnt = "";
            String sCobrador = "";
            String a_line = "";
            String sFull = "";

            while ((nextLine = reader.readNext()) != null) {
                // nextLine[] is an array of values from the line
                //System.out.println(nextLine[0] + nextLine[1] + "etc...");
                a_line = "";
                for (int i = 0; i < nextLine.length; i++) {
                    a_line = a_line + nextLine[i] + ";";
                }
                a_line = a_line.substring(0, a_line.length() - 1);

                sCobrador = nextLine[0];
                if (!sCobrador.equalsIgnoreCase(sCobradorAnt) && (sCobradorAnt == null || sCobradorAnt.equalsIgnoreCase(""))) {
                    sCobradorAnt = nextLine[0];
                    sFull = sFull + a_line + System.getProperty("line.separator");
                } else if (!sCobrador.equalsIgnoreCase(sCobradorAnt) && sCobradorAnt != null && !sCobrador.equalsIgnoreCase("")) {
                    sCobradorAnt = nextLine[0];
                    sFull = sFull + "||-empl-||" + a_line + System.getProperty("line.separator");
                } else {
                    sFull = sFull + a_line + System.getProperty("line.separator");
                }
            }

            String[] splitEmpleado = sFull.split("\\|\\|-empl-\\|\\|");
            System.out.println("splitted.length: " + splitEmpleado.length);
            CSVReader readerEmpleado;
            String[] nextLineEmpleado;
            String a_lineEmpleado = "";
            String sExpendioAnt = "";
            String sExpendio = "";
            String sFullEmpleado = "";

            vRUTAS = new Vector();
            for (int i = 0; i < splitEmpleado.length; i++) {
                if (i==0) {
                    sFullEmpleado = "||-expe-||";
                }
                String sEmpleadoNombre = "";
                String sRutaProducto = "";
                String sRutaZona = "";
                readerEmpleado = new CSVReader(new StringReader(splitEmpleado[i]), ';');
                while ((nextLineEmpleado = readerEmpleado.readNext()) != null) {

                    a_lineEmpleado = "";
                    for (int j = 0; j < nextLineEmpleado.length; j++) {
                        a_lineEmpleado = a_lineEmpleado + nextLineEmpleado[j] + ";";
                        //System.out.println(Arrays.toString(nextLineEmpleado));
                    }
                    a_lineEmpleado = a_lineEmpleado.substring(0, a_lineEmpleado.length() - 1);

                    sExpendio = nextLineEmpleado[4];
                    if (!sExpendio.equalsIgnoreCase(sExpendioAnt) && (sExpendioAnt == null || sExpendioAnt.equalsIgnoreCase(""))) {
                        sExpendioAnt = nextLineEmpleado[4];
                        sFullEmpleado = sFullEmpleado + a_lineEmpleado + System.getProperty("line.separator");
                    } else if (!sExpendio.equalsIgnoreCase(sExpendioAnt) && sExpendioAnt != null && !sExpendioAnt.equalsIgnoreCase("")) {
                        sExpendioAnt = nextLineEmpleado[4];
                        sFullEmpleado = sFullEmpleado + "||-expe-||" + a_lineEmpleado + System.getProperty("line.separator");
                    } else {
                        sFullEmpleado = sFullEmpleado + a_lineEmpleado + System.getProperty("line.separator");
                    }

                    sEmpleadoNombre = nextLineEmpleado[0];
                    sRutaProducto = nextLineEmpleado[16];
                    sRutaZona = nextLineEmpleado[1];
                }

                String[] splitExpendios = sFullEmpleado.split("\\|\\|-expe-\\|\\|");
                System.out.println("splitExpendios.length: "+splitExpendios.length);
                sFullEmpleado = "";


                CSVReader readerExpendio;
                String[] nextLineExpendio;
                String a_lineExpendio = "";

                vExpendios = new Vector();
                for (int m = 1; m < splitExpendios.length; m++) {
                    vFechas = new Vector();
                    String sExpendioNombre = "";
                    String sExpendioDireccion = "";
                    String sExpendioCodigoCliente = "";
                    readerExpendio = new CSVReader(new StringReader(splitExpendios[m]), ';');
                    while ((nextLineExpendio = readerExpendio.readNext()) != null) {

                        contador++;

                        fecha = new Fecha();

                        String sFechaFecha = nextLineExpendio[9];
                        if (sFechaFecha==null || sFechaFecha.equalsIgnoreCase("")) {
                            fecha.SetFecha("");
                        }
                        else {
                            fecha.SetFecha(sFechaFecha);
                        }

                        String sFechaEntregados = nextLineExpendio[10];
                        if (sFechaEntregados==null || sFechaEntregados.equalsIgnoreCase("")) {
                            fecha.SetEntregados(0);
                        }
                        else {
                            int iFechaEntregados = 0;
                            try {
                                iFechaEntregados = Integer.parseInt(sFechaEntregados);
                            }
                            catch(NumberFormatException nfex) {
                                iFechaEntregados = 0;
                                SetMessages(nfex.toString());
                                nfex.printStackTrace();
                            }
                            fecha.SetEntregados(iFechaEntregados);
                        }

                        String sFechaDevueltos = nextLineExpendio[11];
                        if (sFechaDevueltos==null || sFechaDevueltos.equalsIgnoreCase("")) {
                            fecha.SetDevueltos(0);
                        }
                        else {
                            int iFechaDevueltos = 0;
                            try {
                                iFechaDevueltos = Integer.parseInt(sFechaDevueltos);
                            }
                            catch(NumberFormatException nfex) {
                                iFechaDevueltos = 0;
                                SetMessages(nfex.toString());
                                nfex.printStackTrace();
                            }
                            fecha.SetDevueltos(iFechaDevueltos);
                        }

                        String sFechaFaltantes = nextLineExpendio[12];
                        if (sFechaFaltantes==null || sFechaFaltantes.equalsIgnoreCase("")) {
                            fecha.SetFaltantes(0);
                        }
                        else {
                            int iFechaFaltantes = 0;
                            try {
                                iFechaFaltantes = Integer.parseInt(sFechaFaltantes);
                            }
                            catch(NumberFormatException nfex) {
                                iFechaFaltantes = 0;
                                SetMessages(nfex.toString());
                                nfex.printStackTrace();
                            }
                            fecha.SetFaltantes(iFechaFaltantes);
                        }

                        String sFechaValorUnitario = nextLineExpendio[13];
                        if (sFechaValorUnitario==null || sFechaValorUnitario.equalsIgnoreCase("")) {
                            fecha.SetValorUnitario(0);
                        }
                        else {
                            int iFechaValorUnitario = 0;
                            try {
                                iFechaValorUnitario = Integer.parseInt(sFechaValorUnitario);
                            }
                            catch(NumberFormatException nfex) {
                                iFechaValorUnitario = 0;
                                SetMessages(nfex.toString());
                                nfex.printStackTrace();
                            }
                            fecha.SetValorUnitario(iFechaValorUnitario);
                        }

                        fecha.SetAdicionales(0);
                        fecha.SetRestantes(0);

                        fecha.SetVisitado(0);
                        fecha.SetEntrego(0);

                        vFechas.add(fecha);

                        sExpendioNombre = nextLineExpendio[4];
                        sExpendioDireccion = nextLineExpendio[5];
                        sExpendioCodigoCliente = nextLineExpendio[6];
                    }

                    expendio = new Expendio();
                    expendio.SetNombre(sExpendioNombre);
                    expendio.SetDireccion(sExpendioDireccion);
                    expendio.SetCodigoCliente(sExpendioCodigoCliente);
                    expendio.SetCompendio(0);
                    expendio.SetVectorFechas(vFechas);
                    expendio.SetVisitado(0);
                    vExpendios.add(expendio);
                }

                ruta = new Ruta();
                ruta.SetCobrador(sEmpleadoNombre);
                ruta.SetProducto(sRutaProducto);
                ruta.SetZona(sRutaZona);

                // (1) get today's date
                Date today = Calendar.getInstance().getTime();

                // (2) create our "formatter" (our custom format)
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

                // (3) create a new String in the format we want
                String folderName = formatter.format(today);

                // (4) this prints "Folder Name = 2009-09-06-08.23.23"
                //System.out.println("Folder Name = " + folderName);

                //ruta.SetFecha((new Date()).toString());
                ruta.SetFecha(folderName);

                ruta.SetVectorExpendios(vExpendios);

                vRutas.add(ruta);
            }

            rutas.SetVectorRutas(vRutas);

            System.out.println(rutas.JSONObjectToString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return rutas;
    }

    private RutasConsignatarias ParseCSVConsignatarias(String sCSVFile) {
        int contador = 0;
        RutasConsignatarias rutas = new RutasConsignatarias();
        RazonSocialConsignatarias razonsocialconsignatarias = new RazonSocialConsignatarias();
        RutaConsignatarias rutaconsignatarias = new RutaConsignatarias();
        FacturaConsignatarias facturaconsignatarias = new FacturaConsignatarias();
        FechaConsignatarias fechaconsignatarias = new FechaConsignatarias();

        Vector vFechas = new Vector();
        Vector vFacturas = new Vector();
        Vector vRazonesSociales = new Vector();
        Vector vRutas = new Vector();
        Vector vRUTAS = new Vector();

        try {
            String sFechaFechaMov, sFechaEntregas, sFechaDevolucion, sFechaFaltantes, sFechaValorUnitario, sFacturaNumeroF, sRazonSocialNombreRuta, sRutaEmpleado, sRutaZona, sRutaNomPu, sRutaRazonSoc, sRutaCodigoCli;
            sFechaFechaMov = sFechaEntregas = sFechaDevolucion = sFechaFaltantes = sFechaValorUnitario = sFacturaNumeroF = sRazonSocialNombreRuta = sRutaEmpleado = sRutaZona = sRutaNomPu = sRutaRazonSoc = sRutaCodigoCli = "";

            CSVReader reader = new CSVReader(new FileReader(sCSVFile), ';');
            String[] nextLine = reader.readNext();
            String sColumnaPrueba = "";
            //String sColumnaPrueba = nextLine[16];
            try {
                sColumnaPrueba = nextLine[16];
                SetEsEntregar(true);
            } catch (ArrayIndexOutOfBoundsException aioobex) {
                SetEsEntregar(false);
                SetMessages(aioobex.toString());
                aioobex.printStackTrace();
            }

            String sCobradorAnt = "";
            String sCobrador = "";
            String a_line = "";
            String sFull = "||-empl-||";

            while ((nextLine = reader.readNext()) != null) {
                // nextLine[] is an array of values from the line
                //System.out.println(nextLine[0] + nextLine[1] + "etc...");
                a_line = "";
                for (int i = 0; i < nextLine.length; i++) {
                    a_line = a_line + nextLine[i] + ";";
                }
                a_line = a_line.substring(0, a_line.length() - 1);

                sCobrador = nextLine[0];
                if (!sCobrador.equalsIgnoreCase(sCobradorAnt) && (sCobradorAnt == null || sCobradorAnt.equalsIgnoreCase(""))) {
                    sCobradorAnt = nextLine[0];
                    sFull = sFull + a_line + System.getProperty("line.separator");
                } else if (!sCobrador.equalsIgnoreCase(sCobradorAnt) && sCobradorAnt != null && !sCobrador.equalsIgnoreCase("")) {
                    sCobradorAnt = nextLine[0];
                    sFull = sFull + "||-empl-||" + a_line + System.getProperty("line.separator");
                } else {
                    sFull = sFull + a_line + System.getProperty("line.separator");
                }
            }

            String[] splitEmpleado = sFull.split("\\|\\|-empl-\\|\\|");
            System.out.println("splitted.length: " + splitEmpleado.length);
            CSVReader readerEmpleado;
            String[] nextLineEmpleado;
            String a_lineEmpleado = "";
            String sRazonSocAnt = "";
            String sRazonSoc = "";
            String sFullEmpleado = "||-razs-||";

            vRUTAS = new Vector();
            for (int i = 1; i < splitEmpleado.length; i++) {
                sFullEmpleado = "||-razs-||";
                sRazonSocAnt = "";
                sRazonSoc = "";

                /*if (i == 0) {
                    sFullEmpleado = "||-razs-||";
                }*/

                readerEmpleado = new CSVReader(new StringReader(splitEmpleado[i]), ';');
                while ((nextLineEmpleado = readerEmpleado.readNext()) != null) {

                    a_lineEmpleado = "";
                    for (int j = 0; j < nextLineEmpleado.length; j++) {
                        a_lineEmpleado = a_lineEmpleado + nextLineEmpleado[j] + ";";
                        //System.out.println(Arrays.toString(nextLineEmpleado));
                    }
                    a_lineEmpleado = a_lineEmpleado.substring(0, a_lineEmpleado.length() - 1);

                    sRazonSoc = nextLineEmpleado[4];
                    if (!sRazonSoc.equalsIgnoreCase(sRazonSocAnt) && (sRazonSocAnt == null || sRazonSocAnt.equalsIgnoreCase(""))) {
                        sRazonSocAnt = nextLineEmpleado[4];
                        sFullEmpleado = sFullEmpleado + a_lineEmpleado + System.getProperty("line.separator");
                    } else if (!sRazonSoc.equalsIgnoreCase(sRazonSocAnt) && sRazonSocAnt != null && !sRazonSocAnt.equalsIgnoreCase("")) {
                        sRazonSocAnt = nextLineEmpleado[4];
                        sFullEmpleado = sFullEmpleado + "||-razs-||" + a_lineEmpleado + System.getProperty("line.separator");
                    } else {
                        sFullEmpleado = sFullEmpleado + a_lineEmpleado + System.getProperty("line.separator");
                    }
                }


                String[] splitRazonSocs = sFullEmpleado.split("\\|\\|-razs-\\|\\|");
                System.out.println("splitRazonSocs.length: " + splitRazonSocs.length);
                String sNumeroFAnt = "";
                String sNumeroF = "";
                String sFullRazonSoc = "||-fact-||";


                CSVReader readerRazonSoc;
                String[] nextLineRazonSoc;
                String a_lineRazonSoc = "";

                vRazonesSociales = new Vector();
                for (int m = 1; m < splitRazonSocs.length; m++) {
                    sFullRazonSoc = "||-fact-||";
                    //sFullRazonSoc = "";
                    sNumeroFAnt = "";
                    sNumeroF = "";

                    /*if (i == 0) {
                        sFullRazonSoc = "||-fact-||";
                    }*/

                    readerRazonSoc = new CSVReader(new StringReader(splitRazonSocs[m]), ';');

                    while ((nextLineRazonSoc = readerRazonSoc.readNext()) != null) {

                        a_lineRazonSoc = "";
                        for (int n = 0; n < nextLineRazonSoc.length; n++) {
                            a_lineRazonSoc = a_lineRazonSoc + nextLineRazonSoc[n] + ";";
                            //System.out.println(Arrays.toString(nextLineEmpleado));
                        }
                        a_lineRazonSoc = a_lineRazonSoc.substring(0, a_lineRazonSoc.length() - 1);

                        //sNumeroF = nextLineRazonSoc[4];
                        sNumeroF = nextLineRazonSoc[15];
                        if (!sNumeroF.equalsIgnoreCase(sNumeroFAnt) && (sNumeroFAnt == null || sNumeroFAnt.equalsIgnoreCase(""))) {
                            //sNumeroFAnt = nextLineRazonSoc[4];
                            sNumeroFAnt = nextLineRazonSoc[15];
                            sFullRazonSoc = sFullRazonSoc + a_lineRazonSoc + System.getProperty("line.separator");
                        } else if (!sNumeroF.equalsIgnoreCase(sNumeroFAnt) && sNumeroFAnt != null && !sNumeroFAnt.equalsIgnoreCase("")) {
                            //sNumeroFAnt = nextLineRazonSoc[4];
                            sNumeroFAnt = nextLineRazonSoc[15];
                            sFullRazonSoc = sFullRazonSoc + "||-fact-||" + a_lineRazonSoc + System.getProperty("line.separator");
                        } else {
                            sFullRazonSoc = sFullRazonSoc + a_lineRazonSoc + System.getProperty("line.separator");
                        }
                    }


                    String[] splitFacturas = sFullRazonSoc.split("\\|\\|-fact-\\|\\|");
                    System.out.println("splitFacturas.length: " + splitFacturas.length);
                    //sFullEmpleado = "";

                    CSVReader readerFacturas;
                    String[] nextLineFactura;
                    //String a_lineRazonSoc = "";

                    vFacturas = new Vector();
                    for (int o = 1; o < splitFacturas.length; o++) {

                        vFechas = new Vector();

                        readerFacturas = new CSVReader(new StringReader(splitFacturas[o]), ';');
                        while ((nextLineFactura = readerFacturas.readNext()) != null) {

                            contador++;

                            fechaconsignatarias = new FechaConsignatarias();

                            sFechaFechaMov = nextLineFactura[7];
                            if (sFechaFechaMov == null || sFechaFechaMov.equalsIgnoreCase("")) {
                                fechaconsignatarias.SetFecha("");
                            } else {
                                fechaconsignatarias.SetFecha(sFechaFechaMov);
                            }

                            sFechaEntregas = nextLineFactura[8];
                            if (sFechaEntregas == null || sFechaEntregas.equalsIgnoreCase("")) {
                                fechaconsignatarias.SetEntregados(0);
                            } else {
                                int iFechaEntregas = 0;
                                try {
                                    iFechaEntregas = Integer.parseInt(sFechaEntregas);
                                }
                                catch (NumberFormatException nfex) {
                                    iFechaEntregas = 0;
                                    SetMessages(nfex.toString());
                                    nfex.printStackTrace();
                                }
                                fechaconsignatarias.SetEntregados(iFechaEntregas);
                            }

                            sFechaDevolucion = nextLineFactura[9];
                            if (sFechaDevolucion == null || sFechaDevolucion.equalsIgnoreCase("")) {
                                fechaconsignatarias.SetDevueltos(0);
                            } else {
                                int iFechaDevolucion = 0;
                                try {
                                    iFechaDevolucion = Integer.parseInt(sFechaDevolucion);
                                }
                                catch (NumberFormatException nfex) {
                                    iFechaDevolucion = 0;
                                    SetMessages(nfex.toString());
                                    nfex.printStackTrace();
                                }
                                fechaconsignatarias.SetDevueltos(iFechaDevolucion);
                            }

                            sFechaFaltantes = nextLineFactura[10];
                            if (sFechaFaltantes == null || sFechaFaltantes.equalsIgnoreCase("")) {
                                fechaconsignatarias.SetFaltantes(0);
                            } else {
                                int iFechaFaltantes = 0;
                                try {
                                    iFechaFaltantes = Integer.parseInt(sFechaFaltantes);
                                }
                                catch (NumberFormatException nfex) {
                                    iFechaFaltantes = 0;
                                    SetMessages(nfex.toString());
                                    nfex.printStackTrace();
                                }
                                fechaconsignatarias.SetFaltantes(iFechaFaltantes);
                            }

                            fechaconsignatarias.SetSobrantes(0);

                            sFechaValorUnitario = nextLineFactura[11];
                            if (sFechaValorUnitario == null || sFechaValorUnitario.equalsIgnoreCase("")) {
                                fechaconsignatarias.SetValorUnitario(0);
                            } else {
                                int iFechaValorUnitario = 0;
                                try {
                                    iFechaValorUnitario = Integer.parseInt(sFechaValorUnitario);
                                }
                                catch (NumberFormatException nfex) {
                                    iFechaValorUnitario = 0;
                                    SetMessages(nfex.toString());
                                    nfex.printStackTrace();
                                }
                                fechaconsignatarias.SetValorUnitario(iFechaValorUnitario);
                            }

                            fechaconsignatarias.SetAdicionales(0);
                            fechaconsignatarias.SetRestantes(0);

                            fechaconsignatarias.SetVisitado(0);
                            fechaconsignatarias.SetEntrego(0);

                            vFechas.add(fechaconsignatarias);


                            sFacturaNumeroF = nextLineFactura[15];
                            if (sFacturaNumeroF == null || sFacturaNumeroF.equalsIgnoreCase("")) {
                                sFacturaNumeroF = "0";
                            }

                            sRazonSocialNombreRuta = nextLineFactura[2];

                            sRutaEmpleado = nextLineFactura[0];
                            sRutaZona = nextLineFactura[1];
                            sRutaNomPu = nextLineFactura[3];
                            sRutaRazonSoc = nextLineFactura[4];
                            sRutaCodigoCli = nextLineFactura[6];
                        }

                        facturaconsignatarias = new FacturaConsignatarias();

                        facturaconsignatarias.SetNoFactura(sFacturaNumeroF);

                        facturaconsignatarias.SetFechaPago("");

                        facturaconsignatarias.SetCompendio(0);
                        facturaconsignatarias.SetVectorFechas(vFechas);
                        facturaconsignatarias.SetVisitado(0);

                        vFacturas.add(facturaconsignatarias);
                    }

                    razonsocialconsignatarias = new RazonSocialConsignatarias();

                    razonsocialconsignatarias.SetZona(sRutaZona);
                    razonsocialconsignatarias.SetNombreRuta(sRazonSocialNombreRuta);
                    razonsocialconsignatarias.SetConsignataria(sRutaRazonSoc);
                    razonsocialconsignatarias.SetCodigo(sRutaCodigoCli);
                    razonsocialconsignatarias.SetAgencia("");

                    razonsocialconsignatarias.SetVisitado(0);

                    razonsocialconsignatarias.SetVectorFacturas(vFacturas);

                    vRazonesSociales.add(razonsocialconsignatarias);
                }

                rutaconsignatarias = new RutaConsignatarias();

                rutaconsignatarias.SetCobrador(sRutaEmpleado);

                rutaconsignatarias.SetProducto(sRutaNomPu);

                // (1) get today's date
                Date today = Calendar.getInstance().getTime();

                // (2) create our "formatter" (our custom format)
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yy");

                // (3) create a new String in the format we want
                String folderName = formatter.format(today);

                // (4) this prints "Folder Name = 2009-09-06-08.23.23"
                //System.out.println("Folder Name = " + folderName);

                //ruta.SetFecha((new Date()).toString());
                rutaconsignatarias.SetFecha(folderName);

                rutaconsignatarias.SetVectorRazonSocial(vRazonesSociales);
                vRutas.add(rutaconsignatarias);
            }

            rutas.SetVectorRutas(vRutas);
            
            System.out.println(rutas.JSONObjectToString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return rutas;
    }


    private boolean WriteJSONCobradorFile(Rutas rutas, String sAbsoluteDestination, int iContador) {
        try {
            JSONObject joOriginal = new JSONObject(rutas.JSONObjectToString());
            
            //String sFinalFileName = sAbsoluteDestination + System.getProperty("file.separator") + ("COBRAD"+iContador+".json");
            String sFinalFileName = "";
            if (GetEsEntregar()) {
                sFinalFileName = sAbsoluteDestination + System.getProperty("file.separator") + ("EXPENT"+iContador+".json");
            }
            else {
                sFinalFileName = sAbsoluteDestination + System.getProperty("file.separator") + ("EXPCOB"+iContador+".json");
            }
            
            BufferedWriter out = new BufferedWriter(new FileWriter(sFinalFileName));
            out.write(joOriginal.toString());
            out.close();

            SetMessages("Escrito archivo '"+sFinalFileName+"'.");
            SetSuccess(true);
        } catch (JSONException jsonex) {
            SetMessages(jsonex.toString());
            SetSuccess(false);
            jsonex.printStackTrace();
        } catch (IOException ioex) {
            SetMessages(ioex.toString());
            SetSuccess(false);
            ioex.printStackTrace();
        } catch (Exception ex) {
            SetMessages(ex.toString());
            SetSuccess(false);
            ex.printStackTrace();
        }

        return GetSuccess();
    }

    private boolean WriteJSONCobradorFileConsignatarias(RutasConsignatarias rutasconsignatarias, String sAbsoluteDestination, int iContador) {
        try {
            JSONObject joOriginal = new JSONObject(rutasconsignatarias.JSONObjectToString());

            //String sFinalFileName = sAbsoluteDestination + System.getProperty("file.separator") + ("CONSIG"+iContador+".json");
            String sFinalFileName = "";
            if (GetEsEntregar()) {
                sFinalFileName = sAbsoluteDestination + System.getProperty("file.separator") + ("CONENT"+iContador+".json");
            }
            else {
                sFinalFileName = sAbsoluteDestination + System.getProperty("file.separator") + ("CONCOB"+iContador+".json");
            }
            
            BufferedWriter out = new BufferedWriter(new FileWriter(sFinalFileName));
            out.write(joOriginal.toString());
            out.close();

            SetMessages("Escrito archivo '"+sFinalFileName+"'.");
            SetSuccess(true);
        } catch (JSONException jsonex) {
            SetMessages(jsonex.toString());
            SetSuccess(false);
            jsonex.printStackTrace();
        } catch (IOException ioex) {
            SetMessages(ioex.toString());
            SetSuccess(false);
            ioex.printStackTrace();
        } catch (Exception ex) {
            SetMessages(ex.toString());
            SetSuccess(false);
            ex.printStackTrace();
        }

        return GetSuccess();
    }
}
